version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - UPLOAD_DIR=uploads
      - CHROMA_PERSIST_DIR=chroma_db
      - MAX_FILE_SIZE=10485760
      - ALLOWED_EXTENSIONS=pdf,docx,txt,md
      - CORS_ORIGINS=http://localhost:3000,http://localhost:5173
    volumes:
      - ./backend/uploads:/app/uploads
      - ./backend/chroma_db:/app/chroma_db
      - ./backend:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    depends_on: []

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://localhost:8000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev
    depends_on:
      - backend

networks:
  default:
    name: doc-analyzer-network 